//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Position {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Position.SPosition")]
    public interface SPosition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Update", ReplyAction="http://tempuri.org/SPosition/UpdateResponse")]
        void Update(string newname, string newsalary, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Update", ReplyAction="http://tempuri.org/SPosition/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string newname, string newsalary, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Insert", ReplyAction="http://tempuri.org/SPosition/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Insert", ReplyAction="http://tempuri.org/SPosition/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_P_Name", ReplyAction="http://tempuri.org/SPosition/get_P_NameResponse")]
        string get_P_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_P_Name", ReplyAction="http://tempuri.org/SPosition/get_P_NameResponse")]
        System.Threading.Tasks.Task<string> get_P_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/set_P_Name", ReplyAction="http://tempuri.org/SPosition/set_P_NameResponse")]
        void set_P_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/set_P_Name", ReplyAction="http://tempuri.org/SPosition/set_P_NameResponse")]
        System.Threading.Tasks.Task set_P_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_P_Salary", ReplyAction="http://tempuri.org/SPosition/get_P_SalaryResponse")]
        string get_P_Salary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_P_Salary", ReplyAction="http://tempuri.org/SPosition/get_P_SalaryResponse")]
        System.Threading.Tasks.Task<string> get_P_SalaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/set_P_Salary", ReplyAction="http://tempuri.org/SPosition/set_P_SalaryResponse")]
        void set_P_Salary(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/set_P_Salary", ReplyAction="http://tempuri.org/SPosition/set_P_SalaryResponse")]
        System.Threading.Tasks.Task set_P_SalaryAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Delete", ReplyAction="http://tempuri.org/SPosition/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/Delete", ReplyAction="http://tempuri.org/SPosition/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/toString", ReplyAction="http://tempuri.org/SPosition/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/toString", ReplyAction="http://tempuri.org/SPosition/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get", ReplyAction="http://tempuri.org/SPosition/getResponse")]
        string get(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get", ReplyAction="http://tempuri.org/SPosition/getResponse")]
        System.Threading.Tasks.Task<string> getAsync(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_s", ReplyAction="http://tempuri.org/SPosition/get_sResponse")]
        string get_s();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/get_s", ReplyAction="http://tempuri.org/SPosition/get_sResponse")]
        System.Threading.Tasks.Task<string> get_sAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/getByName", ReplyAction="http://tempuri.org/SPosition/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPosition/getByName", ReplyAction="http://tempuri.org/SPosition/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPositionChannel : LibraryClient.Position.SPosition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPositionClient : System.ServiceModel.ClientBase<LibraryClient.Position.SPosition>, LibraryClient.Position.SPosition {
        
        public SPositionClient() {
        }
        
        public SPositionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPositionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPositionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPositionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Update(string newname, string newsalary, string name) {
            base.Channel.Update(newname, newsalary, name);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string newname, string newsalary, string name) {
            return base.Channel.UpdateAsync(newname, newsalary, name);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public string get_P_Name() {
            return base.Channel.get_P_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_P_NameAsync() {
            return base.Channel.get_P_NameAsync();
        }
        
        public void set_P_Name(string value) {
            base.Channel.set_P_Name(value);
        }
        
        public System.Threading.Tasks.Task set_P_NameAsync(string value) {
            return base.Channel.set_P_NameAsync(value);
        }
        
        public string get_P_Salary() {
            return base.Channel.get_P_Salary();
        }
        
        public System.Threading.Tasks.Task<string> get_P_SalaryAsync() {
            return base.Channel.get_P_SalaryAsync();
        }
        
        public void set_P_Salary(string value) {
            base.Channel.set_P_Salary(value);
        }
        
        public System.Threading.Tasks.Task set_P_SalaryAsync(string value) {
            return base.Channel.set_P_SalaryAsync(value);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get(int page) {
            return base.Channel.get(page);
        }
        
        public System.Threading.Tasks.Task<string> getAsync(int page) {
            return base.Channel.getAsync(page);
        }
        
        public string get_s() {
            return base.Channel.get_s();
        }
        
        public System.Threading.Tasks.Task<string> get_sAsync() {
            return base.Channel.get_sAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
