//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Librarian {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Librarian.ServLibrarian")]
    public interface ServLibrarian {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_MyHuman", ReplyAction="http://tempuri.org/ServLibrarian/get_MyHumanResponse")]
        string get_MyHuman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_MyHuman", ReplyAction="http://tempuri.org/ServLibrarian/get_MyHumanResponse")]
        System.Threading.Tasks.Task<string> get_MyHumanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_MyHuman", ReplyAction="http://tempuri.org/ServLibrarian/set_MyHumanResponse")]
        void set_MyHuman(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_MyHuman", ReplyAction="http://tempuri.org/ServLibrarian/set_MyHumanResponse")]
        System.Threading.Tasks.Task set_MyHumanAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_Date_of_employment", ReplyAction="http://tempuri.org/ServLibrarian/get_Date_of_employmentResponse")]
        string get_Date_of_employment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_Date_of_employment", ReplyAction="http://tempuri.org/ServLibrarian/get_Date_of_employmentResponse")]
        System.Threading.Tasks.Task<string> get_Date_of_employmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_Date_of_employment", ReplyAction="http://tempuri.org/ServLibrarian/set_Date_of_employmentResponse")]
        void set_Date_of_employment(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_Date_of_employment", ReplyAction="http://tempuri.org/ServLibrarian/set_Date_of_employmentResponse")]
        System.Threading.Tasks.Task set_Date_of_employmentAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_Telephone", ReplyAction="http://tempuri.org/ServLibrarian/get_TelephoneResponse")]
        string get_Telephone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/get_Telephone", ReplyAction="http://tempuri.org/ServLibrarian/get_TelephoneResponse")]
        System.Threading.Tasks.Task<string> get_TelephoneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_Telephone", ReplyAction="http://tempuri.org/ServLibrarian/set_TelephoneResponse")]
        void set_Telephone(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/set_Telephone", ReplyAction="http://tempuri.org/ServLibrarian/set_TelephoneResponse")]
        System.Threading.Tasks.Task set_TelephoneAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/getAllLibrarians", ReplyAction="http://tempuri.org/ServLibrarian/getAllLibrariansResponse")]
        string getAllLibrarians(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/getAllLibrarians", ReplyAction="http://tempuri.org/ServLibrarian/getAllLibrariansResponse")]
        System.Threading.Tasks.Task<string> getAllLibrariansAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/SaveLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/SaveLibrarianResponse")]
        void SaveLibrarian();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/SaveLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/SaveLibrarianResponse")]
        System.Threading.Tasks.Task SaveLibrarianAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/DeleteLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/DeleteLibrarianResponse")]
        void DeleteLibrarian(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/DeleteLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/DeleteLibrarianResponse")]
        System.Threading.Tasks.Task DeleteLibrarianAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/UpdateLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/UpdateLibrarianResponse")]
        void UpdateLibrarian(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLibrarian/UpdateLibrarian", ReplyAction="http://tempuri.org/ServLibrarian/UpdateLibrarianResponse")]
        System.Threading.Tasks.Task UpdateLibrarianAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServLibrarianChannel : LibraryClient.Librarian.ServLibrarian, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServLibrarianClient : System.ServiceModel.ClientBase<LibraryClient.Librarian.ServLibrarian>, LibraryClient.Librarian.ServLibrarian {
        
        public ServLibrarianClient() {
        }
        
        public ServLibrarianClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServLibrarianClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLibrarianClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLibrarianClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_MyHuman() {
            return base.Channel.get_MyHuman();
        }
        
        public System.Threading.Tasks.Task<string> get_MyHumanAsync() {
            return base.Channel.get_MyHumanAsync();
        }
        
        public void set_MyHuman(string value) {
            base.Channel.set_MyHuman(value);
        }
        
        public System.Threading.Tasks.Task set_MyHumanAsync(string value) {
            return base.Channel.set_MyHumanAsync(value);
        }
        
        public string get_Date_of_employment() {
            return base.Channel.get_Date_of_employment();
        }
        
        public System.Threading.Tasks.Task<string> get_Date_of_employmentAsync() {
            return base.Channel.get_Date_of_employmentAsync();
        }
        
        public void set_Date_of_employment(string value) {
            base.Channel.set_Date_of_employment(value);
        }
        
        public System.Threading.Tasks.Task set_Date_of_employmentAsync(string value) {
            return base.Channel.set_Date_of_employmentAsync(value);
        }
        
        public string get_Telephone() {
            return base.Channel.get_Telephone();
        }
        
        public System.Threading.Tasks.Task<string> get_TelephoneAsync() {
            return base.Channel.get_TelephoneAsync();
        }
        
        public void set_Telephone(string value) {
            base.Channel.set_Telephone(value);
        }
        
        public System.Threading.Tasks.Task set_TelephoneAsync(string value) {
            return base.Channel.set_TelephoneAsync(value);
        }
        
        public string getAllLibrarians(string num) {
            return base.Channel.getAllLibrarians(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllLibrariansAsync(string num) {
            return base.Channel.getAllLibrariansAsync(num);
        }
        
        public void SaveLibrarian() {
            base.Channel.SaveLibrarian();
        }
        
        public System.Threading.Tasks.Task SaveLibrarianAsync() {
            return base.Channel.SaveLibrarianAsync();
        }
        
        public void DeleteLibrarian(string index) {
            base.Channel.DeleteLibrarian(index);
        }
        
        public System.Threading.Tasks.Task DeleteLibrarianAsync(string index) {
            return base.Channel.DeleteLibrarianAsync(index);
        }
        
        public void UpdateLibrarian(string index) {
            base.Channel.UpdateLibrarian(index);
        }
        
        public System.Threading.Tasks.Task UpdateLibrarianAsync(string index) {
            return base.Channel.UpdateLibrarianAsync(index);
        }
    }
}
