//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Genre {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Genre.ServGenre")]
    public interface ServGenre {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/get_Name", ReplyAction="http://tempuri.org/ServGenre/get_NameResponse")]
        string get_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/get_Name", ReplyAction="http://tempuri.org/ServGenre/get_NameResponse")]
        System.Threading.Tasks.Task<string> get_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/set_Name", ReplyAction="http://tempuri.org/ServGenre/set_NameResponse")]
        void set_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/set_Name", ReplyAction="http://tempuri.org/ServGenre/set_NameResponse")]
        System.Threading.Tasks.Task set_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/get_Discription", ReplyAction="http://tempuri.org/ServGenre/get_DiscriptionResponse")]
        string get_Discription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/get_Discription", ReplyAction="http://tempuri.org/ServGenre/get_DiscriptionResponse")]
        System.Threading.Tasks.Task<string> get_DiscriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/set_Discription", ReplyAction="http://tempuri.org/ServGenre/set_DiscriptionResponse")]
        void set_Discription(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/set_Discription", ReplyAction="http://tempuri.org/ServGenre/set_DiscriptionResponse")]
        System.Threading.Tasks.Task set_DiscriptionAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/getAllGenres", ReplyAction="http://tempuri.org/ServGenre/getAllGenresResponse")]
        string getAllGenres(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/getAllGenres", ReplyAction="http://tempuri.org/ServGenre/getAllGenresResponse")]
        System.Threading.Tasks.Task<string> getAllGenresAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/SaveGenre", ReplyAction="http://tempuri.org/ServGenre/SaveGenreResponse")]
        void SaveGenre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/SaveGenre", ReplyAction="http://tempuri.org/ServGenre/SaveGenreResponse")]
        System.Threading.Tasks.Task SaveGenreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/DeleteGenre", ReplyAction="http://tempuri.org/ServGenre/DeleteGenreResponse")]
        void DeleteGenre(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/DeleteGenre", ReplyAction="http://tempuri.org/ServGenre/DeleteGenreResponse")]
        System.Threading.Tasks.Task DeleteGenreAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/UpdateGenre", ReplyAction="http://tempuri.org/ServGenre/UpdateGenreResponse")]
        void UpdateGenre(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServGenre/UpdateGenre", ReplyAction="http://tempuri.org/ServGenre/UpdateGenreResponse")]
        System.Threading.Tasks.Task UpdateGenreAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServGenreChannel : LibraryClient.Genre.ServGenre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServGenreClient : System.ServiceModel.ClientBase<LibraryClient.Genre.ServGenre>, LibraryClient.Genre.ServGenre {
        
        public ServGenreClient() {
        }
        
        public ServGenreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServGenreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServGenreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServGenreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Name() {
            return base.Channel.get_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_NameAsync() {
            return base.Channel.get_NameAsync();
        }
        
        public void set_Name(string value) {
            base.Channel.set_Name(value);
        }
        
        public System.Threading.Tasks.Task set_NameAsync(string value) {
            return base.Channel.set_NameAsync(value);
        }
        
        public string get_Discription() {
            return base.Channel.get_Discription();
        }
        
        public System.Threading.Tasks.Task<string> get_DiscriptionAsync() {
            return base.Channel.get_DiscriptionAsync();
        }
        
        public void set_Discription(string value) {
            base.Channel.set_Discription(value);
        }
        
        public System.Threading.Tasks.Task set_DiscriptionAsync(string value) {
            return base.Channel.set_DiscriptionAsync(value);
        }
        
        public string getAllGenres(string num) {
            return base.Channel.getAllGenres(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllGenresAsync(string num) {
            return base.Channel.getAllGenresAsync(num);
        }
        
        public void SaveGenre() {
            base.Channel.SaveGenre();
        }
        
        public System.Threading.Tasks.Task SaveGenreAsync() {
            return base.Channel.SaveGenreAsync();
        }
        
        public void DeleteGenre(string index) {
            base.Channel.DeleteGenre(index);
        }
        
        public System.Threading.Tasks.Task DeleteGenreAsync(string index) {
            return base.Channel.DeleteGenreAsync(index);
        }
        
        public void UpdateGenre(string index) {
            base.Channel.UpdateGenre(index);
        }
        
        public System.Threading.Tasks.Task UpdateGenreAsync(string index) {
            return base.Channel.UpdateGenreAsync(index);
        }
    }
}
