//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Book {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Book.ServBook")]
    public interface ServBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_MyAuthor", ReplyAction="http://tempuri.org/ServBook/get_MyAuthorResponse")]
        string get_MyAuthor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_MyAuthor", ReplyAction="http://tempuri.org/ServBook/get_MyAuthorResponse")]
        System.Threading.Tasks.Task<string> get_MyAuthorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_MyAuthor", ReplyAction="http://tempuri.org/ServBook/set_MyAuthorResponse")]
        void set_MyAuthor(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_MyAuthor", ReplyAction="http://tempuri.org/ServBook/set_MyAuthorResponse")]
        System.Threading.Tasks.Task set_MyAuthorAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_MyGenre", ReplyAction="http://tempuri.org/ServBook/get_MyGenreResponse")]
        string get_MyGenre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_MyGenre", ReplyAction="http://tempuri.org/ServBook/get_MyGenreResponse")]
        System.Threading.Tasks.Task<string> get_MyGenreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_MyGenre", ReplyAction="http://tempuri.org/ServBook/set_MyGenreResponse")]
        void set_MyGenre(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_MyGenre", ReplyAction="http://tempuri.org/ServBook/set_MyGenreResponse")]
        System.Threading.Tasks.Task set_MyGenreAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Name", ReplyAction="http://tempuri.org/ServBook/get_NameResponse")]
        string get_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Name", ReplyAction="http://tempuri.org/ServBook/get_NameResponse")]
        System.Threading.Tasks.Task<string> get_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Name", ReplyAction="http://tempuri.org/ServBook/set_NameResponse")]
        void set_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Name", ReplyAction="http://tempuri.org/ServBook/set_NameResponse")]
        System.Threading.Tasks.Task set_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Year", ReplyAction="http://tempuri.org/ServBook/get_YearResponse")]
        string get_Year();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Year", ReplyAction="http://tempuri.org/ServBook/get_YearResponse")]
        System.Threading.Tasks.Task<string> get_YearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Year", ReplyAction="http://tempuri.org/ServBook/set_YearResponse")]
        void set_Year(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Year", ReplyAction="http://tempuri.org/ServBook/set_YearResponse")]
        System.Threading.Tasks.Task set_YearAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Publishing", ReplyAction="http://tempuri.org/ServBook/get_PublishingResponse")]
        string get_Publishing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Publishing", ReplyAction="http://tempuri.org/ServBook/get_PublishingResponse")]
        System.Threading.Tasks.Task<string> get_PublishingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Publishing", ReplyAction="http://tempuri.org/ServBook/set_PublishingResponse")]
        void set_Publishing(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Publishing", ReplyAction="http://tempuri.org/ServBook/set_PublishingResponse")]
        System.Threading.Tasks.Task set_PublishingAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Paper_number", ReplyAction="http://tempuri.org/ServBook/get_Paper_numberResponse")]
        string get_Paper_number();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Paper_number", ReplyAction="http://tempuri.org/ServBook/get_Paper_numberResponse")]
        System.Threading.Tasks.Task<string> get_Paper_numberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Paper_number", ReplyAction="http://tempuri.org/ServBook/set_Paper_numberResponse")]
        void set_Paper_number(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Paper_number", ReplyAction="http://tempuri.org/ServBook/set_Paper_numberResponse")]
        System.Threading.Tasks.Task set_Paper_numberAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Book_number", ReplyAction="http://tempuri.org/ServBook/get_Book_numberResponse")]
        string get_Book_number();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/get_Book_number", ReplyAction="http://tempuri.org/ServBook/get_Book_numberResponse")]
        System.Threading.Tasks.Task<string> get_Book_numberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Book_number", ReplyAction="http://tempuri.org/ServBook/set_Book_numberResponse")]
        void set_Book_number(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/set_Book_number", ReplyAction="http://tempuri.org/ServBook/set_Book_numberResponse")]
        System.Threading.Tasks.Task set_Book_numberAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getAllBooks", ReplyAction="http://tempuri.org/ServBook/getAllBooksResponse")]
        string getAllBooks(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getAllBooks", ReplyAction="http://tempuri.org/ServBook/getAllBooksResponse")]
        System.Threading.Tasks.Task<string> getAllBooksAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getBookByName", ReplyAction="http://tempuri.org/ServBook/getBookByNameResponse")]
        string getBookByName(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getBookByName", ReplyAction="http://tempuri.org/ServBook/getBookByNameResponse")]
        System.Threading.Tasks.Task<string> getBookByNameAsync(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/SaveBook", ReplyAction="http://tempuri.org/ServBook/SaveBookResponse")]
        void SaveBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/SaveBook", ReplyAction="http://tempuri.org/ServBook/SaveBookResponse")]
        System.Threading.Tasks.Task SaveBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/DeleteBook", ReplyAction="http://tempuri.org/ServBook/DeleteBookResponse")]
        void DeleteBook(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/DeleteBook", ReplyAction="http://tempuri.org/ServBook/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/UpdateBook", ReplyAction="http://tempuri.org/ServBook/UpdateBookResponse")]
        void UpdateBook(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/UpdateBook", ReplyAction="http://tempuri.org/ServBook/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/BookToString", ReplyAction="http://tempuri.org/ServBook/BookToStringResponse")]
        string BookToString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/BookToString", ReplyAction="http://tempuri.org/ServBook/BookToStringResponse")]
        System.Threading.Tasks.Task<string> BookToStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getBookList", ReplyAction="http://tempuri.org/ServBook/getBookListResponse")]
        string getBookList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServBook/getBookList", ReplyAction="http://tempuri.org/ServBook/getBookListResponse")]
        System.Threading.Tasks.Task<string> getBookListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServBookChannel : LibraryClient.Book.ServBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServBookClient : System.ServiceModel.ClientBase<LibraryClient.Book.ServBook>, LibraryClient.Book.ServBook {
        
        public ServBookClient() {
        }
        
        public ServBookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServBookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServBookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_MyAuthor() {
            return base.Channel.get_MyAuthor();
        }
        
        public System.Threading.Tasks.Task<string> get_MyAuthorAsync() {
            return base.Channel.get_MyAuthorAsync();
        }
        
        public void set_MyAuthor(string value) {
            base.Channel.set_MyAuthor(value);
        }
        
        public System.Threading.Tasks.Task set_MyAuthorAsync(string value) {
            return base.Channel.set_MyAuthorAsync(value);
        }
        
        public string get_MyGenre() {
            return base.Channel.get_MyGenre();
        }
        
        public System.Threading.Tasks.Task<string> get_MyGenreAsync() {
            return base.Channel.get_MyGenreAsync();
        }
        
        public void set_MyGenre(string value) {
            base.Channel.set_MyGenre(value);
        }
        
        public System.Threading.Tasks.Task set_MyGenreAsync(string value) {
            return base.Channel.set_MyGenreAsync(value);
        }
        
        public string get_Name() {
            return base.Channel.get_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_NameAsync() {
            return base.Channel.get_NameAsync();
        }
        
        public void set_Name(string value) {
            base.Channel.set_Name(value);
        }
        
        public System.Threading.Tasks.Task set_NameAsync(string value) {
            return base.Channel.set_NameAsync(value);
        }
        
        public string get_Year() {
            return base.Channel.get_Year();
        }
        
        public System.Threading.Tasks.Task<string> get_YearAsync() {
            return base.Channel.get_YearAsync();
        }
        
        public void set_Year(string value) {
            base.Channel.set_Year(value);
        }
        
        public System.Threading.Tasks.Task set_YearAsync(string value) {
            return base.Channel.set_YearAsync(value);
        }
        
        public string get_Publishing() {
            return base.Channel.get_Publishing();
        }
        
        public System.Threading.Tasks.Task<string> get_PublishingAsync() {
            return base.Channel.get_PublishingAsync();
        }
        
        public void set_Publishing(string value) {
            base.Channel.set_Publishing(value);
        }
        
        public System.Threading.Tasks.Task set_PublishingAsync(string value) {
            return base.Channel.set_PublishingAsync(value);
        }
        
        public string get_Paper_number() {
            return base.Channel.get_Paper_number();
        }
        
        public System.Threading.Tasks.Task<string> get_Paper_numberAsync() {
            return base.Channel.get_Paper_numberAsync();
        }
        
        public void set_Paper_number(string value) {
            base.Channel.set_Paper_number(value);
        }
        
        public System.Threading.Tasks.Task set_Paper_numberAsync(string value) {
            return base.Channel.set_Paper_numberAsync(value);
        }
        
        public string get_Book_number() {
            return base.Channel.get_Book_number();
        }
        
        public System.Threading.Tasks.Task<string> get_Book_numberAsync() {
            return base.Channel.get_Book_numberAsync();
        }
        
        public void set_Book_number(string value) {
            base.Channel.set_Book_number(value);
        }
        
        public System.Threading.Tasks.Task set_Book_numberAsync(string value) {
            return base.Channel.set_Book_numberAsync(value);
        }
        
        public string getAllBooks(string num) {
            return base.Channel.getAllBooks(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllBooksAsync(string num) {
            return base.Channel.getAllBooksAsync(num);
        }
        
        public string getBookByName(string n) {
            return base.Channel.getBookByName(n);
        }
        
        public System.Threading.Tasks.Task<string> getBookByNameAsync(string n) {
            return base.Channel.getBookByNameAsync(n);
        }
        
        public void SaveBook() {
            base.Channel.SaveBook();
        }
        
        public System.Threading.Tasks.Task SaveBookAsync() {
            return base.Channel.SaveBookAsync();
        }
        
        public void DeleteBook(string index) {
            base.Channel.DeleteBook(index);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(string index) {
            return base.Channel.DeleteBookAsync(index);
        }
        
        public void UpdateBook(string index) {
            base.Channel.UpdateBook(index);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(string index) {
            return base.Channel.UpdateBookAsync(index);
        }
        
        public string BookToString() {
            return base.Channel.BookToString();
        }
        
        public System.Threading.Tasks.Task<string> BookToStringAsync() {
            return base.Channel.BookToStringAsync();
        }
        
        public string getBookList() {
            return base.Channel.getBookList();
        }
        
        public System.Threading.Tasks.Task<string> getBookListAsync() {
            return base.Channel.getBookListAsync();
        }
    }
}
