//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Profile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Profile.SProfile")]
    public interface SProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/get_Profile_Name", ReplyAction="http://tempuri.org/SProfile/get_Profile_NameResponse")]
        string get_Profile_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/get_Profile_Name", ReplyAction="http://tempuri.org/SProfile/get_Profile_NameResponse")]
        System.Threading.Tasks.Task<string> get_Profile_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/set_Profile_Name", ReplyAction="http://tempuri.org/SProfile/set_Profile_NameResponse")]
        void set_Profile_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/set_Profile_Name", ReplyAction="http://tempuri.org/SProfile/set_Profile_NameResponse")]
        System.Threading.Tasks.Task set_Profile_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Insert", ReplyAction="http://tempuri.org/SProfile/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Insert", ReplyAction="http://tempuri.org/SProfile/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Update", ReplyAction="http://tempuri.org/SProfile/UpdateResponse")]
        void Update(string name, string newname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Update", ReplyAction="http://tempuri.org/SProfile/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string name, string newname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Delete", ReplyAction="http://tempuri.org/SProfile/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/Delete", ReplyAction="http://tempuri.org/SProfile/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/toString", ReplyAction="http://tempuri.org/SProfile/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/toString", ReplyAction="http://tempuri.org/SProfile/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/get", ReplyAction="http://tempuri.org/SProfile/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/get", ReplyAction="http://tempuri.org/SProfile/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/getByName", ReplyAction="http://tempuri.org/SProfile/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProfile/getByName", ReplyAction="http://tempuri.org/SProfile/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SProfileChannel : LibraryClient.Profile.SProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SProfileClient : System.ServiceModel.ClientBase<LibraryClient.Profile.SProfile>, LibraryClient.Profile.SProfile {
        
        public SProfileClient() {
        }
        
        public SProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Profile_Name() {
            return base.Channel.get_Profile_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_Profile_NameAsync() {
            return base.Channel.get_Profile_NameAsync();
        }
        
        public void set_Profile_Name(string value) {
            base.Channel.set_Profile_Name(value);
        }
        
        public System.Threading.Tasks.Task set_Profile_NameAsync(string value) {
            return base.Channel.set_Profile_NameAsync(value);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public void Update(string name, string newname) {
            base.Channel.Update(name, newname);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string name, string newname) {
            return base.Channel.UpdateAsync(name, newname);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
