//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Arrangement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Arrangement.ServArrangement")]
    public interface ServArrangement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/get_Place", ReplyAction="http://tempuri.org/ServArrangement/get_PlaceResponse")]
        string get_Place();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/get_Place", ReplyAction="http://tempuri.org/ServArrangement/get_PlaceResponse")]
        System.Threading.Tasks.Task<string> get_PlaceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/set_Place", ReplyAction="http://tempuri.org/ServArrangement/set_PlaceResponse")]
        void set_Place(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/set_Place", ReplyAction="http://tempuri.org/ServArrangement/set_PlaceResponse")]
        System.Threading.Tasks.Task set_PlaceAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/getAllArrangements", ReplyAction="http://tempuri.org/ServArrangement/getAllArrangementsResponse")]
        string getAllArrangements(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/getAllArrangements", ReplyAction="http://tempuri.org/ServArrangement/getAllArrangementsResponse")]
        System.Threading.Tasks.Task<string> getAllArrangementsAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/SaveArrangement", ReplyAction="http://tempuri.org/ServArrangement/SaveArrangementResponse")]
        void SaveArrangement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/SaveArrangement", ReplyAction="http://tempuri.org/ServArrangement/SaveArrangementResponse")]
        System.Threading.Tasks.Task SaveArrangementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/DeleteArrangement", ReplyAction="http://tempuri.org/ServArrangement/DeleteArrangementResponse")]
        void DeleteArrangement(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/DeleteArrangement", ReplyAction="http://tempuri.org/ServArrangement/DeleteArrangementResponse")]
        System.Threading.Tasks.Task DeleteArrangementAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/UpdateArrangement", ReplyAction="http://tempuri.org/ServArrangement/UpdateArrangementResponse")]
        void UpdateArrangement(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/UpdateArrangement", ReplyAction="http://tempuri.org/ServArrangement/UpdateArrangementResponse")]
        System.Threading.Tasks.Task UpdateArrangementAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/getAll", ReplyAction="http://tempuri.org/ServArrangement/getAllResponse")]
        string getAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServArrangement/getAll", ReplyAction="http://tempuri.org/ServArrangement/getAllResponse")]
        System.Threading.Tasks.Task<string> getAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServArrangementChannel : LibraryClient.Arrangement.ServArrangement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServArrangementClient : System.ServiceModel.ClientBase<LibraryClient.Arrangement.ServArrangement>, LibraryClient.Arrangement.ServArrangement {
        
        public ServArrangementClient() {
        }
        
        public ServArrangementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServArrangementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServArrangementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServArrangementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Place() {
            return base.Channel.get_Place();
        }
        
        public System.Threading.Tasks.Task<string> get_PlaceAsync() {
            return base.Channel.get_PlaceAsync();
        }
        
        public void set_Place(string value) {
            base.Channel.set_Place(value);
        }
        
        public System.Threading.Tasks.Task set_PlaceAsync(string value) {
            return base.Channel.set_PlaceAsync(value);
        }
        
        public string getAllArrangements(string num) {
            return base.Channel.getAllArrangements(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllArrangementsAsync(string num) {
            return base.Channel.getAllArrangementsAsync(num);
        }
        
        public void SaveArrangement() {
            base.Channel.SaveArrangement();
        }
        
        public System.Threading.Tasks.Task SaveArrangementAsync() {
            return base.Channel.SaveArrangementAsync();
        }
        
        public void DeleteArrangement(string index) {
            base.Channel.DeleteArrangement(index);
        }
        
        public System.Threading.Tasks.Task DeleteArrangementAsync(string index) {
            return base.Channel.DeleteArrangementAsync(index);
        }
        
        public void UpdateArrangement(string index) {
            base.Channel.UpdateArrangement(index);
        }
        
        public System.Threading.Tasks.Task UpdateArrangementAsync(string index) {
            return base.Channel.UpdateArrangementAsync(index);
        }
        
        public string getAll() {
            return base.Channel.getAll();
        }
        
        public System.Threading.Tasks.Task<string> getAllAsync() {
            return base.Channel.getAllAsync();
        }
    }
}
