//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Country {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Country.SCountry")]
    public interface SCountry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Name", ReplyAction="http://tempuri.org/SCountry/get_Country_NameResponse")]
        string get_Country_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Name", ReplyAction="http://tempuri.org/SCountry/get_Country_NameResponse")]
        System.Threading.Tasks.Task<string> get_Country_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Name", ReplyAction="http://tempuri.org/SCountry/set_Country_NameResponse")]
        void set_Country_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Name", ReplyAction="http://tempuri.org/SCountry/set_Country_NameResponse")]
        System.Threading.Tasks.Task set_Country_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Continent", ReplyAction="http://tempuri.org/SCountry/get_Country_ContinentResponse")]
        string get_Country_Continent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Continent", ReplyAction="http://tempuri.org/SCountry/get_Country_ContinentResponse")]
        System.Threading.Tasks.Task<string> get_Country_ContinentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Continent", ReplyAction="http://tempuri.org/SCountry/set_Country_ContinentResponse")]
        void set_Country_Continent(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Continent", ReplyAction="http://tempuri.org/SCountry/set_Country_ContinentResponse")]
        System.Threading.Tasks.Task set_Country_ContinentAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Square", ReplyAction="http://tempuri.org/SCountry/get_Country_SquareResponse")]
        string get_Country_Square();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_Country_Square", ReplyAction="http://tempuri.org/SCountry/get_Country_SquareResponse")]
        System.Threading.Tasks.Task<string> get_Country_SquareAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Square", ReplyAction="http://tempuri.org/SCountry/set_Country_SquareResponse")]
        void set_Country_Square(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/set_Country_Square", ReplyAction="http://tempuri.org/SCountry/set_Country_SquareResponse")]
        System.Threading.Tasks.Task set_Country_SquareAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Insert", ReplyAction="http://tempuri.org/SCountry/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Insert", ReplyAction="http://tempuri.org/SCountry/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Update", ReplyAction="http://tempuri.org/SCountry/UpdateResponse")]
        void Update(string newname, string name, string continent, string square);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Update", ReplyAction="http://tempuri.org/SCountry/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string newname, string name, string continent, string square);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Delete", ReplyAction="http://tempuri.org/SCountry/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/Delete", ReplyAction="http://tempuri.org/SCountry/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/toString", ReplyAction="http://tempuri.org/SCountry/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/toString", ReplyAction="http://tempuri.org/SCountry/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get", ReplyAction="http://tempuri.org/SCountry/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get", ReplyAction="http://tempuri.org/SCountry/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_name", ReplyAction="http://tempuri.org/SCountry/get_nameResponse")]
        string get_name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/get_name", ReplyAction="http://tempuri.org/SCountry/get_nameResponse")]
        System.Threading.Tasks.Task<string> get_nameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/getByName", ReplyAction="http://tempuri.org/SCountry/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCountry/getByName", ReplyAction="http://tempuri.org/SCountry/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCountryChannel : LibraryClient.Country.SCountry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCountryClient : System.ServiceModel.ClientBase<LibraryClient.Country.SCountry>, LibraryClient.Country.SCountry {
        
        public SCountryClient() {
        }
        
        public SCountryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCountryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCountryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCountryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Country_Name() {
            return base.Channel.get_Country_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_Country_NameAsync() {
            return base.Channel.get_Country_NameAsync();
        }
        
        public void set_Country_Name(string value) {
            base.Channel.set_Country_Name(value);
        }
        
        public System.Threading.Tasks.Task set_Country_NameAsync(string value) {
            return base.Channel.set_Country_NameAsync(value);
        }
        
        public string get_Country_Continent() {
            return base.Channel.get_Country_Continent();
        }
        
        public System.Threading.Tasks.Task<string> get_Country_ContinentAsync() {
            return base.Channel.get_Country_ContinentAsync();
        }
        
        public void set_Country_Continent(string value) {
            base.Channel.set_Country_Continent(value);
        }
        
        public System.Threading.Tasks.Task set_Country_ContinentAsync(string value) {
            return base.Channel.set_Country_ContinentAsync(value);
        }
        
        public string get_Country_Square() {
            return base.Channel.get_Country_Square();
        }
        
        public System.Threading.Tasks.Task<string> get_Country_SquareAsync() {
            return base.Channel.get_Country_SquareAsync();
        }
        
        public void set_Country_Square(string value) {
            base.Channel.set_Country_Square(value);
        }
        
        public System.Threading.Tasks.Task set_Country_SquareAsync(string value) {
            return base.Channel.set_Country_SquareAsync(value);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public void Update(string newname, string name, string continent, string square) {
            base.Channel.Update(newname, name, continent, square);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string newname, string name, string continent, string square) {
            return base.Channel.UpdateAsync(newname, name, continent, square);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string get_name() {
            return base.Channel.get_name();
        }
        
        public System.Threading.Tasks.Task<string> get_nameAsync() {
            return base.Channel.get_nameAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
