//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Factory {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Factory.SFactory")]
    public interface SFactory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Name", ReplyAction="http://tempuri.org/SFactory/get_Factory_NameResponse")]
        string get_Factory_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Name", ReplyAction="http://tempuri.org/SFactory/get_Factory_NameResponse")]
        System.Threading.Tasks.Task<string> get_Factory_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Name", ReplyAction="http://tempuri.org/SFactory/set_Factory_NameResponse")]
        void set_Factory_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Name", ReplyAction="http://tempuri.org/SFactory/set_Factory_NameResponse")]
        System.Threading.Tasks.Task set_Factory_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Address", ReplyAction="http://tempuri.org/SFactory/get_Factory_AddressResponse")]
        string get_Factory_Address();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Address", ReplyAction="http://tempuri.org/SFactory/get_Factory_AddressResponse")]
        System.Threading.Tasks.Task<string> get_Factory_AddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Address", ReplyAction="http://tempuri.org/SFactory/set_Factory_AddressResponse")]
        void set_Factory_Address(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Address", ReplyAction="http://tempuri.org/SFactory/set_Factory_AddressResponse")]
        System.Threading.Tasks.Task set_Factory_AddressAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Country", ReplyAction="http://tempuri.org/SFactory/get_Factory_CountryResponse")]
        string get_Factory_Country();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_Factory_Country", ReplyAction="http://tempuri.org/SFactory/get_Factory_CountryResponse")]
        System.Threading.Tasks.Task<string> get_Factory_CountryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Country", ReplyAction="http://tempuri.org/SFactory/set_Factory_CountryResponse")]
        void set_Factory_Country(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/set_Factory_Country", ReplyAction="http://tempuri.org/SFactory/set_Factory_CountryResponse")]
        System.Threading.Tasks.Task set_Factory_CountryAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Insert", ReplyAction="http://tempuri.org/SFactory/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Insert", ReplyAction="http://tempuri.org/SFactory/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Update", ReplyAction="http://tempuri.org/SFactory/UpdateResponse")]
        void Update(string newname, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Update", ReplyAction="http://tempuri.org/SFactory/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string newname, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Delete", ReplyAction="http://tempuri.org/SFactory/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/Delete", ReplyAction="http://tempuri.org/SFactory/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/toString", ReplyAction="http://tempuri.org/SFactory/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/toString", ReplyAction="http://tempuri.org/SFactory/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get", ReplyAction="http://tempuri.org/SFactory/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get", ReplyAction="http://tempuri.org/SFactory/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_name", ReplyAction="http://tempuri.org/SFactory/get_nameResponse")]
        string get_name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/get_name", ReplyAction="http://tempuri.org/SFactory/get_nameResponse")]
        System.Threading.Tasks.Task<string> get_nameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/getByName", ReplyAction="http://tempuri.org/SFactory/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFactory/getByName", ReplyAction="http://tempuri.org/SFactory/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SFactoryChannel : LibraryClient.Factory.SFactory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SFactoryClient : System.ServiceModel.ClientBase<LibraryClient.Factory.SFactory>, LibraryClient.Factory.SFactory {
        
        public SFactoryClient() {
        }
        
        public SFactoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SFactoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFactoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Factory_Name() {
            return base.Channel.get_Factory_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_Factory_NameAsync() {
            return base.Channel.get_Factory_NameAsync();
        }
        
        public void set_Factory_Name(string value) {
            base.Channel.set_Factory_Name(value);
        }
        
        public System.Threading.Tasks.Task set_Factory_NameAsync(string value) {
            return base.Channel.set_Factory_NameAsync(value);
        }
        
        public string get_Factory_Address() {
            return base.Channel.get_Factory_Address();
        }
        
        public System.Threading.Tasks.Task<string> get_Factory_AddressAsync() {
            return base.Channel.get_Factory_AddressAsync();
        }
        
        public void set_Factory_Address(string value) {
            base.Channel.set_Factory_Address(value);
        }
        
        public System.Threading.Tasks.Task set_Factory_AddressAsync(string value) {
            return base.Channel.set_Factory_AddressAsync(value);
        }
        
        public string get_Factory_Country() {
            return base.Channel.get_Factory_Country();
        }
        
        public System.Threading.Tasks.Task<string> get_Factory_CountryAsync() {
            return base.Channel.get_Factory_CountryAsync();
        }
        
        public void set_Factory_Country(string value) {
            base.Channel.set_Factory_Country(value);
        }
        
        public System.Threading.Tasks.Task set_Factory_CountryAsync(string value) {
            return base.Channel.set_Factory_CountryAsync(value);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public void Update(string newname, string name, string address) {
            base.Channel.Update(newname, name, address);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string newname, string name, string address) {
            return base.Channel.UpdateAsync(newname, name, address);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string get_name() {
            return base.Channel.get_name();
        }
        
        public System.Threading.Tasks.Task<string> get_nameAsync() {
            return base.Channel.get_nameAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
