//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Location {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Location.ServLocation")]
    public interface ServLocation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyBook", ReplyAction="http://tempuri.org/ServLocation/get_MyBookResponse")]
        string get_MyBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyBook", ReplyAction="http://tempuri.org/ServLocation/get_MyBookResponse")]
        System.Threading.Tasks.Task<string> get_MyBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyBook", ReplyAction="http://tempuri.org/ServLocation/set_MyBookResponse")]
        void set_MyBook(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyBook", ReplyAction="http://tempuri.org/ServLocation/set_MyBookResponse")]
        System.Threading.Tasks.Task set_MyBookAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyFloor", ReplyAction="http://tempuri.org/ServLocation/get_MyFloorResponse")]
        string get_MyFloor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyFloor", ReplyAction="http://tempuri.org/ServLocation/get_MyFloorResponse")]
        System.Threading.Tasks.Task<string> get_MyFloorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyFloor", ReplyAction="http://tempuri.org/ServLocation/set_MyFloorResponse")]
        void set_MyFloor(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyFloor", ReplyAction="http://tempuri.org/ServLocation/set_MyFloorResponse")]
        System.Threading.Tasks.Task set_MyFloorAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyArrangement", ReplyAction="http://tempuri.org/ServLocation/get_MyArrangementResponse")]
        string get_MyArrangement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_MyArrangement", ReplyAction="http://tempuri.org/ServLocation/get_MyArrangementResponse")]
        System.Threading.Tasks.Task<string> get_MyArrangementAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyArrangement", ReplyAction="http://tempuri.org/ServLocation/set_MyArrangementResponse")]
        void set_MyArrangement(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_MyArrangement", ReplyAction="http://tempuri.org/ServLocation/set_MyArrangementResponse")]
        System.Threading.Tasks.Task set_MyArrangementAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_Sector", ReplyAction="http://tempuri.org/ServLocation/get_SectorResponse")]
        string get_Sector();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/get_Sector", ReplyAction="http://tempuri.org/ServLocation/get_SectorResponse")]
        System.Threading.Tasks.Task<string> get_SectorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_Sector", ReplyAction="http://tempuri.org/ServLocation/set_SectorResponse")]
        void set_Sector(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/set_Sector", ReplyAction="http://tempuri.org/ServLocation/set_SectorResponse")]
        System.Threading.Tasks.Task set_SectorAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/getAllLocations", ReplyAction="http://tempuri.org/ServLocation/getAllLocationsResponse")]
        string getAllLocations(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/getAllLocations", ReplyAction="http://tempuri.org/ServLocation/getAllLocationsResponse")]
        System.Threading.Tasks.Task<string> getAllLocationsAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/SaveLocation", ReplyAction="http://tempuri.org/ServLocation/SaveLocationResponse")]
        void SaveLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/SaveLocation", ReplyAction="http://tempuri.org/ServLocation/SaveLocationResponse")]
        System.Threading.Tasks.Task SaveLocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/DeleteLocation", ReplyAction="http://tempuri.org/ServLocation/DeleteLocationResponse")]
        void DeleteLocation(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/DeleteLocation", ReplyAction="http://tempuri.org/ServLocation/DeleteLocationResponse")]
        System.Threading.Tasks.Task DeleteLocationAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/UpdateLocation", ReplyAction="http://tempuri.org/ServLocation/UpdateLocationResponse")]
        void UpdateLocation(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServLocation/UpdateLocation", ReplyAction="http://tempuri.org/ServLocation/UpdateLocationResponse")]
        System.Threading.Tasks.Task UpdateLocationAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServLocationChannel : LibraryClient.Location.ServLocation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServLocationClient : System.ServiceModel.ClientBase<LibraryClient.Location.ServLocation>, LibraryClient.Location.ServLocation {
        
        public ServLocationClient() {
        }
        
        public ServLocationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServLocationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLocationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_MyBook() {
            return base.Channel.get_MyBook();
        }
        
        public System.Threading.Tasks.Task<string> get_MyBookAsync() {
            return base.Channel.get_MyBookAsync();
        }
        
        public void set_MyBook(string value) {
            base.Channel.set_MyBook(value);
        }
        
        public System.Threading.Tasks.Task set_MyBookAsync(string value) {
            return base.Channel.set_MyBookAsync(value);
        }
        
        public string get_MyFloor() {
            return base.Channel.get_MyFloor();
        }
        
        public System.Threading.Tasks.Task<string> get_MyFloorAsync() {
            return base.Channel.get_MyFloorAsync();
        }
        
        public void set_MyFloor(string value) {
            base.Channel.set_MyFloor(value);
        }
        
        public System.Threading.Tasks.Task set_MyFloorAsync(string value) {
            return base.Channel.set_MyFloorAsync(value);
        }
        
        public string get_MyArrangement() {
            return base.Channel.get_MyArrangement();
        }
        
        public System.Threading.Tasks.Task<string> get_MyArrangementAsync() {
            return base.Channel.get_MyArrangementAsync();
        }
        
        public void set_MyArrangement(string value) {
            base.Channel.set_MyArrangement(value);
        }
        
        public System.Threading.Tasks.Task set_MyArrangementAsync(string value) {
            return base.Channel.set_MyArrangementAsync(value);
        }
        
        public string get_Sector() {
            return base.Channel.get_Sector();
        }
        
        public System.Threading.Tasks.Task<string> get_SectorAsync() {
            return base.Channel.get_SectorAsync();
        }
        
        public void set_Sector(string value) {
            base.Channel.set_Sector(value);
        }
        
        public System.Threading.Tasks.Task set_SectorAsync(string value) {
            return base.Channel.set_SectorAsync(value);
        }
        
        public string getAllLocations(string num) {
            return base.Channel.getAllLocations(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllLocationsAsync(string num) {
            return base.Channel.getAllLocationsAsync(num);
        }
        
        public void SaveLocation() {
            base.Channel.SaveLocation();
        }
        
        public System.Threading.Tasks.Task SaveLocationAsync() {
            return base.Channel.SaveLocationAsync();
        }
        
        public void DeleteLocation(string index) {
            base.Channel.DeleteLocation(index);
        }
        
        public System.Threading.Tasks.Task DeleteLocationAsync(string index) {
            return base.Channel.DeleteLocationAsync(index);
        }
        
        public void UpdateLocation(string index) {
            base.Channel.UpdateLocation(index);
        }
        
        public System.Threading.Tasks.Task UpdateLocationAsync(string index) {
            return base.Channel.UpdateLocationAsync(index);
        }
    }
}
