//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Product {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Product.SProduct")]
    public interface SProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get_Product_Name", ReplyAction="http://tempuri.org/SProduct/get_Product_NameResponse")]
        string get_Product_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get_Product_Name", ReplyAction="http://tempuri.org/SProduct/get_Product_NameResponse")]
        System.Threading.Tasks.Task<string> get_Product_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/set_Product_Name", ReplyAction="http://tempuri.org/SProduct/set_Product_NameResponse")]
        void set_Product_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/set_Product_Name", ReplyAction="http://tempuri.org/SProduct/set_Product_NameResponse")]
        System.Threading.Tasks.Task set_Product_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get_Product_Cost", ReplyAction="http://tempuri.org/SProduct/get_Product_CostResponse")]
        string get_Product_Cost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get_Product_Cost", ReplyAction="http://tempuri.org/SProduct/get_Product_CostResponse")]
        System.Threading.Tasks.Task<string> get_Product_CostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/set_Product_Cost", ReplyAction="http://tempuri.org/SProduct/set_Product_CostResponse")]
        void set_Product_Cost(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/set_Product_Cost", ReplyAction="http://tempuri.org/SProduct/set_Product_CostResponse")]
        System.Threading.Tasks.Task set_Product_CostAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Insert", ReplyAction="http://tempuri.org/SProduct/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Insert", ReplyAction="http://tempuri.org/SProduct/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Update", ReplyAction="http://tempuri.org/SProduct/UpdateResponse")]
        void Update(string newname, string name, string cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Update", ReplyAction="http://tempuri.org/SProduct/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string newname, string name, string cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Delete", ReplyAction="http://tempuri.org/SProduct/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/Delete", ReplyAction="http://tempuri.org/SProduct/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/toString", ReplyAction="http://tempuri.org/SProduct/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/toString", ReplyAction="http://tempuri.org/SProduct/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get", ReplyAction="http://tempuri.org/SProduct/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/get", ReplyAction="http://tempuri.org/SProduct/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/getByName", ReplyAction="http://tempuri.org/SProduct/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SProduct/getByName", ReplyAction="http://tempuri.org/SProduct/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SProductChannel : LibraryClient.Product.SProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SProductClient : System.ServiceModel.ClientBase<LibraryClient.Product.SProduct>, LibraryClient.Product.SProduct {
        
        public SProductClient() {
        }
        
        public SProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Product_Name() {
            return base.Channel.get_Product_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_Product_NameAsync() {
            return base.Channel.get_Product_NameAsync();
        }
        
        public void set_Product_Name(string value) {
            base.Channel.set_Product_Name(value);
        }
        
        public System.Threading.Tasks.Task set_Product_NameAsync(string value) {
            return base.Channel.set_Product_NameAsync(value);
        }
        
        public string get_Product_Cost() {
            return base.Channel.get_Product_Cost();
        }
        
        public System.Threading.Tasks.Task<string> get_Product_CostAsync() {
            return base.Channel.get_Product_CostAsync();
        }
        
        public void set_Product_Cost(string value) {
            base.Channel.set_Product_Cost(value);
        }
        
        public System.Threading.Tasks.Task set_Product_CostAsync(string value) {
            return base.Channel.set_Product_CostAsync(value);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public void Update(string newname, string name, string cost) {
            base.Channel.Update(newname, name, cost);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string newname, string name, string cost) {
            return base.Channel.UpdateAsync(newname, name, cost);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
