//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Reader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reader.ServReader")]
    public interface ServReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_MyHuman", ReplyAction="http://tempuri.org/ServReader/get_MyHumanResponse")]
        string get_MyHuman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_MyHuman", ReplyAction="http://tempuri.org/ServReader/get_MyHumanResponse")]
        System.Threading.Tasks.Task<string> get_MyHumanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_MyHuman", ReplyAction="http://tempuri.org/ServReader/set_MyHumanResponse")]
        void set_MyHuman(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_MyHuman", ReplyAction="http://tempuri.org/ServReader/set_MyHumanResponse")]
        System.Threading.Tasks.Task set_MyHumanAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Address", ReplyAction="http://tempuri.org/ServReader/get_AddressResponse")]
        string get_Address();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Address", ReplyAction="http://tempuri.org/ServReader/get_AddressResponse")]
        System.Threading.Tasks.Task<string> get_AddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Address", ReplyAction="http://tempuri.org/ServReader/set_AddressResponse")]
        void set_Address(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Address", ReplyAction="http://tempuri.org/ServReader/set_AddressResponse")]
        System.Threading.Tasks.Task set_AddressAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Telephone", ReplyAction="http://tempuri.org/ServReader/get_TelephoneResponse")]
        string get_Telephone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Telephone", ReplyAction="http://tempuri.org/ServReader/get_TelephoneResponse")]
        System.Threading.Tasks.Task<string> get_TelephoneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Telephone", ReplyAction="http://tempuri.org/ServReader/set_TelephoneResponse")]
        void set_Telephone(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Telephone", ReplyAction="http://tempuri.org/ServReader/set_TelephoneResponse")]
        System.Threading.Tasks.Task set_TelephoneAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Date_of_registration", ReplyAction="http://tempuri.org/ServReader/get_Date_of_registrationResponse")]
        string get_Date_of_registration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Date_of_registration", ReplyAction="http://tempuri.org/ServReader/get_Date_of_registrationResponse")]
        System.Threading.Tasks.Task<string> get_Date_of_registrationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Date_of_registration", ReplyAction="http://tempuri.org/ServReader/set_Date_of_registrationResponse")]
        void set_Date_of_registration(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Date_of_registration", ReplyAction="http://tempuri.org/ServReader/set_Date_of_registrationResponse")]
        System.Threading.Tasks.Task set_Date_of_registrationAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_MyStatus", ReplyAction="http://tempuri.org/ServReader/get_MyStatusResponse")]
        string get_MyStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_MyStatus", ReplyAction="http://tempuri.org/ServReader/get_MyStatusResponse")]
        System.Threading.Tasks.Task<string> get_MyStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_MyStatus", ReplyAction="http://tempuri.org/ServReader/set_MyStatusResponse")]
        void set_MyStatus(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_MyStatus", ReplyAction="http://tempuri.org/ServReader/set_MyStatusResponse")]
        System.Threading.Tasks.Task set_MyStatusAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Penalties", ReplyAction="http://tempuri.org/ServReader/get_PenaltiesResponse")]
        string get_Penalties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/get_Penalties", ReplyAction="http://tempuri.org/ServReader/get_PenaltiesResponse")]
        System.Threading.Tasks.Task<string> get_PenaltiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Penalties", ReplyAction="http://tempuri.org/ServReader/set_PenaltiesResponse")]
        void set_Penalties(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/set_Penalties", ReplyAction="http://tempuri.org/ServReader/set_PenaltiesResponse")]
        System.Threading.Tasks.Task set_PenaltiesAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/getAllReaders", ReplyAction="http://tempuri.org/ServReader/getAllReadersResponse")]
        string getAllReaders(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/getAllReaders", ReplyAction="http://tempuri.org/ServReader/getAllReadersResponse")]
        System.Threading.Tasks.Task<string> getAllReadersAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/SaveReader", ReplyAction="http://tempuri.org/ServReader/SaveReaderResponse")]
        void SaveReader();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/SaveReader", ReplyAction="http://tempuri.org/ServReader/SaveReaderResponse")]
        System.Threading.Tasks.Task SaveReaderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/DeleteReader", ReplyAction="http://tempuri.org/ServReader/DeleteReaderResponse")]
        void DeleteReader(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/DeleteReader", ReplyAction="http://tempuri.org/ServReader/DeleteReaderResponse")]
        System.Threading.Tasks.Task DeleteReaderAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/UpdateReader", ReplyAction="http://tempuri.org/ServReader/UpdateReaderResponse")]
        void UpdateReader(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServReader/UpdateReader", ReplyAction="http://tempuri.org/ServReader/UpdateReaderResponse")]
        System.Threading.Tasks.Task UpdateReaderAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServReaderChannel : LibraryClient.Reader.ServReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServReaderClient : System.ServiceModel.ClientBase<LibraryClient.Reader.ServReader>, LibraryClient.Reader.ServReader {
        
        public ServReaderClient() {
        }
        
        public ServReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_MyHuman() {
            return base.Channel.get_MyHuman();
        }
        
        public System.Threading.Tasks.Task<string> get_MyHumanAsync() {
            return base.Channel.get_MyHumanAsync();
        }
        
        public void set_MyHuman(string value) {
            base.Channel.set_MyHuman(value);
        }
        
        public System.Threading.Tasks.Task set_MyHumanAsync(string value) {
            return base.Channel.set_MyHumanAsync(value);
        }
        
        public string get_Address() {
            return base.Channel.get_Address();
        }
        
        public System.Threading.Tasks.Task<string> get_AddressAsync() {
            return base.Channel.get_AddressAsync();
        }
        
        public void set_Address(string value) {
            base.Channel.set_Address(value);
        }
        
        public System.Threading.Tasks.Task set_AddressAsync(string value) {
            return base.Channel.set_AddressAsync(value);
        }
        
        public string get_Telephone() {
            return base.Channel.get_Telephone();
        }
        
        public System.Threading.Tasks.Task<string> get_TelephoneAsync() {
            return base.Channel.get_TelephoneAsync();
        }
        
        public void set_Telephone(string value) {
            base.Channel.set_Telephone(value);
        }
        
        public System.Threading.Tasks.Task set_TelephoneAsync(string value) {
            return base.Channel.set_TelephoneAsync(value);
        }
        
        public string get_Date_of_registration() {
            return base.Channel.get_Date_of_registration();
        }
        
        public System.Threading.Tasks.Task<string> get_Date_of_registrationAsync() {
            return base.Channel.get_Date_of_registrationAsync();
        }
        
        public void set_Date_of_registration(string value) {
            base.Channel.set_Date_of_registration(value);
        }
        
        public System.Threading.Tasks.Task set_Date_of_registrationAsync(string value) {
            return base.Channel.set_Date_of_registrationAsync(value);
        }
        
        public string get_MyStatus() {
            return base.Channel.get_MyStatus();
        }
        
        public System.Threading.Tasks.Task<string> get_MyStatusAsync() {
            return base.Channel.get_MyStatusAsync();
        }
        
        public void set_MyStatus(string value) {
            base.Channel.set_MyStatus(value);
        }
        
        public System.Threading.Tasks.Task set_MyStatusAsync(string value) {
            return base.Channel.set_MyStatusAsync(value);
        }
        
        public string get_Penalties() {
            return base.Channel.get_Penalties();
        }
        
        public System.Threading.Tasks.Task<string> get_PenaltiesAsync() {
            return base.Channel.get_PenaltiesAsync();
        }
        
        public void set_Penalties(string value) {
            base.Channel.set_Penalties(value);
        }
        
        public System.Threading.Tasks.Task set_PenaltiesAsync(string value) {
            return base.Channel.set_PenaltiesAsync(value);
        }
        
        public string getAllReaders(string num) {
            return base.Channel.getAllReaders(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllReadersAsync(string num) {
            return base.Channel.getAllReadersAsync(num);
        }
        
        public void SaveReader() {
            base.Channel.SaveReader();
        }
        
        public System.Threading.Tasks.Task SaveReaderAsync() {
            return base.Channel.SaveReaderAsync();
        }
        
        public void DeleteReader(string index) {
            base.Channel.DeleteReader(index);
        }
        
        public System.Threading.Tasks.Task DeleteReaderAsync(string index) {
            return base.Channel.DeleteReaderAsync(index);
        }
        
        public void UpdateReader(string index) {
            base.Channel.UpdateReader(index);
        }
        
        public System.Threading.Tasks.Task UpdateReaderAsync(string index) {
            return base.Channel.UpdateReaderAsync(index);
        }
    }
}
