//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Cost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cost.SCost")]
    public interface SCost {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Product", ReplyAction="http://tempuri.org/SCost/get_Cost_ProductResponse")]
        string get_Cost_Product();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Product", ReplyAction="http://tempuri.org/SCost/get_Cost_ProductResponse")]
        System.Threading.Tasks.Task<string> get_Cost_ProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Product", ReplyAction="http://tempuri.org/SCost/set_Cost_ProductResponse")]
        void set_Cost_Product(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Product", ReplyAction="http://tempuri.org/SCost/set_Cost_ProductResponse")]
        System.Threading.Tasks.Task set_Cost_ProductAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Old_cost", ReplyAction="http://tempuri.org/SCost/get_Cost_Old_costResponse")]
        string get_Cost_Old_cost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Old_cost", ReplyAction="http://tempuri.org/SCost/get_Cost_Old_costResponse")]
        System.Threading.Tasks.Task<string> get_Cost_Old_costAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Old_cost", ReplyAction="http://tempuri.org/SCost/set_Cost_Old_costResponse")]
        void set_Cost_Old_cost(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Old_cost", ReplyAction="http://tempuri.org/SCost/set_Cost_Old_costResponse")]
        System.Threading.Tasks.Task set_Cost_Old_costAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_New_cost", ReplyAction="http://tempuri.org/SCost/get_Cost_New_costResponse")]
        string get_Cost_New_cost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_New_cost", ReplyAction="http://tempuri.org/SCost/get_Cost_New_costResponse")]
        System.Threading.Tasks.Task<string> get_Cost_New_costAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_New_cost", ReplyAction="http://tempuri.org/SCost/set_Cost_New_costResponse")]
        void set_Cost_New_cost(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_New_cost", ReplyAction="http://tempuri.org/SCost/set_Cost_New_costResponse")]
        System.Threading.Tasks.Task set_Cost_New_costAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Date_C", ReplyAction="http://tempuri.org/SCost/get_Cost_Date_CResponse")]
        string get_Cost_Date_C();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get_Cost_Date_C", ReplyAction="http://tempuri.org/SCost/get_Cost_Date_CResponse")]
        System.Threading.Tasks.Task<string> get_Cost_Date_CAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Date_C", ReplyAction="http://tempuri.org/SCost/set_Cost_Date_CResponse")]
        void set_Cost_Date_C(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/set_Cost_Date_C", ReplyAction="http://tempuri.org/SCost/set_Cost_Date_CResponse")]
        System.Threading.Tasks.Task set_Cost_Date_CAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/toString", ReplyAction="http://tempuri.org/SCost/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/toString", ReplyAction="http://tempuri.org/SCost/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get", ReplyAction="http://tempuri.org/SCost/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/get", ReplyAction="http://tempuri.org/SCost/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/getByName", ReplyAction="http://tempuri.org/SCost/getByNameResponse")]
        string getByName(string product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCost/getByName", ReplyAction="http://tempuri.org/SCost/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCostChannel : LibraryClient.Cost.SCost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCostClient : System.ServiceModel.ClientBase<LibraryClient.Cost.SCost>, LibraryClient.Cost.SCost {
        
        public SCostClient() {
        }
        
        public SCostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Cost_Product() {
            return base.Channel.get_Cost_Product();
        }
        
        public System.Threading.Tasks.Task<string> get_Cost_ProductAsync() {
            return base.Channel.get_Cost_ProductAsync();
        }
        
        public void set_Cost_Product(string value) {
            base.Channel.set_Cost_Product(value);
        }
        
        public System.Threading.Tasks.Task set_Cost_ProductAsync(string value) {
            return base.Channel.set_Cost_ProductAsync(value);
        }
        
        public string get_Cost_Old_cost() {
            return base.Channel.get_Cost_Old_cost();
        }
        
        public System.Threading.Tasks.Task<string> get_Cost_Old_costAsync() {
            return base.Channel.get_Cost_Old_costAsync();
        }
        
        public void set_Cost_Old_cost(string value) {
            base.Channel.set_Cost_Old_cost(value);
        }
        
        public System.Threading.Tasks.Task set_Cost_Old_costAsync(string value) {
            return base.Channel.set_Cost_Old_costAsync(value);
        }
        
        public string get_Cost_New_cost() {
            return base.Channel.get_Cost_New_cost();
        }
        
        public System.Threading.Tasks.Task<string> get_Cost_New_costAsync() {
            return base.Channel.get_Cost_New_costAsync();
        }
        
        public void set_Cost_New_cost(string value) {
            base.Channel.set_Cost_New_cost(value);
        }
        
        public System.Threading.Tasks.Task set_Cost_New_costAsync(string value) {
            return base.Channel.set_Cost_New_costAsync(value);
        }
        
        public string get_Cost_Date_C() {
            return base.Channel.get_Cost_Date_C();
        }
        
        public System.Threading.Tasks.Task<string> get_Cost_Date_CAsync() {
            return base.Channel.get_Cost_Date_CAsync();
        }
        
        public void set_Cost_Date_C(string value) {
            base.Channel.set_Cost_Date_C(value);
        }
        
        public System.Threading.Tasks.Task set_Cost_Date_CAsync(string value) {
            return base.Channel.set_Cost_Date_CAsync(value);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string getByName(string product) {
            return base.Channel.getByName(product);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string product) {
            return base.Channel.getByNameAsync(product);
        }
    }
}
