//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Shop {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Shop.SShop")]
    public interface SShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Name", ReplyAction="http://tempuri.org/SShop/get_Shop_NameResponse")]
        string get_Shop_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Name", ReplyAction="http://tempuri.org/SShop/get_Shop_NameResponse")]
        System.Threading.Tasks.Task<string> get_Shop_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Name", ReplyAction="http://tempuri.org/SShop/set_Shop_NameResponse")]
        void set_Shop_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Name", ReplyAction="http://tempuri.org/SShop/set_Shop_NameResponse")]
        System.Threading.Tasks.Task set_Shop_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Profile", ReplyAction="http://tempuri.org/SShop/get_Shop_ProfileResponse")]
        string get_Shop_Profile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Profile", ReplyAction="http://tempuri.org/SShop/get_Shop_ProfileResponse")]
        System.Threading.Tasks.Task<string> get_Shop_ProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Profile", ReplyAction="http://tempuri.org/SShop/set_Shop_ProfileResponse")]
        void set_Shop_Profile(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Profile", ReplyAction="http://tempuri.org/SShop/set_Shop_ProfileResponse")]
        System.Threading.Tasks.Task set_Shop_ProfileAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Address", ReplyAction="http://tempuri.org/SShop/get_Shop_AddressResponse")]
        string get_Shop_Address();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get_Shop_Address", ReplyAction="http://tempuri.org/SShop/get_Shop_AddressResponse")]
        System.Threading.Tasks.Task<string> get_Shop_AddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Address", ReplyAction="http://tempuri.org/SShop/set_Shop_AddressResponse")]
        void set_Shop_Address(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/set_Shop_Address", ReplyAction="http://tempuri.org/SShop/set_Shop_AddressResponse")]
        System.Threading.Tasks.Task set_Shop_AddressAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Insert", ReplyAction="http://tempuri.org/SShop/InsertResponse")]
        void Insert();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Insert", ReplyAction="http://tempuri.org/SShop/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Update", ReplyAction="http://tempuri.org/SShop/UpdateResponse")]
        void Update(string newname, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Update", ReplyAction="http://tempuri.org/SShop/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string newname, string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Delete", ReplyAction="http://tempuri.org/SShop/DeleteResponse")]
        void Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/Delete", ReplyAction="http://tempuri.org/SShop/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/toString", ReplyAction="http://tempuri.org/SShop/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/toString", ReplyAction="http://tempuri.org/SShop/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get", ReplyAction="http://tempuri.org/SShop/getResponse")]
        string get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/get", ReplyAction="http://tempuri.org/SShop/getResponse")]
        System.Threading.Tasks.Task<string> getAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/getByName", ReplyAction="http://tempuri.org/SShop/getByNameResponse")]
        string getByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SShop/getByName", ReplyAction="http://tempuri.org/SShop/getByNameResponse")]
        System.Threading.Tasks.Task<string> getByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SShopChannel : LibraryClient.Shop.SShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SShopClient : System.ServiceModel.ClientBase<LibraryClient.Shop.SShop>, LibraryClient.Shop.SShop {
        
        public SShopClient() {
        }
        
        public SShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Shop_Name() {
            return base.Channel.get_Shop_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_Shop_NameAsync() {
            return base.Channel.get_Shop_NameAsync();
        }
        
        public void set_Shop_Name(string value) {
            base.Channel.set_Shop_Name(value);
        }
        
        public System.Threading.Tasks.Task set_Shop_NameAsync(string value) {
            return base.Channel.set_Shop_NameAsync(value);
        }
        
        public string get_Shop_Profile() {
            return base.Channel.get_Shop_Profile();
        }
        
        public System.Threading.Tasks.Task<string> get_Shop_ProfileAsync() {
            return base.Channel.get_Shop_ProfileAsync();
        }
        
        public void set_Shop_Profile(string value) {
            base.Channel.set_Shop_Profile(value);
        }
        
        public System.Threading.Tasks.Task set_Shop_ProfileAsync(string value) {
            return base.Channel.set_Shop_ProfileAsync(value);
        }
        
        public string get_Shop_Address() {
            return base.Channel.get_Shop_Address();
        }
        
        public System.Threading.Tasks.Task<string> get_Shop_AddressAsync() {
            return base.Channel.get_Shop_AddressAsync();
        }
        
        public void set_Shop_Address(string value) {
            base.Channel.set_Shop_Address(value);
        }
        
        public System.Threading.Tasks.Task set_Shop_AddressAsync(string value) {
            return base.Channel.set_Shop_AddressAsync(value);
        }
        
        public void Insert() {
            base.Channel.Insert();
        }
        
        public System.Threading.Tasks.Task InsertAsync() {
            return base.Channel.InsertAsync();
        }
        
        public void Update(string newname, string name, string address) {
            base.Channel.Update(newname, name, address);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string newname, string name, string address) {
            return base.Channel.UpdateAsync(newname, name, address);
        }
        
        public void Delete(string name) {
            base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public string get() {
            return base.Channel.get();
        }
        
        public System.Threading.Tasks.Task<string> getAsync() {
            return base.Channel.getAsync();
        }
        
        public string getByName(string name) {
            return base.Channel.getByName(name);
        }
        
        public System.Threading.Tasks.Task<string> getByNameAsync(string name) {
            return base.Channel.getByNameAsync(name);
        }
    }
}
