//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Author {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Author.ServAuthor")]
    public interface ServAuthor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_MyHuman", ReplyAction="http://tempuri.org/ServAuthor/get_MyHumanResponse")]
        string get_MyHuman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_MyHuman", ReplyAction="http://tempuri.org/ServAuthor/get_MyHumanResponse")]
        System.Threading.Tasks.Task<string> get_MyHumanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_MyHuman", ReplyAction="http://tempuri.org/ServAuthor/set_MyHumanResponse")]
        void set_MyHuman(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_MyHuman", ReplyAction="http://tempuri.org/ServAuthor/set_MyHumanResponse")]
        System.Threading.Tasks.Task set_MyHumanAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_Date_of_birdth", ReplyAction="http://tempuri.org/ServAuthor/get_Date_of_birdthResponse")]
        string get_Date_of_birdth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_Date_of_birdth", ReplyAction="http://tempuri.org/ServAuthor/get_Date_of_birdthResponse")]
        System.Threading.Tasks.Task<string> get_Date_of_birdthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_Date_of_birdth", ReplyAction="http://tempuri.org/ServAuthor/set_Date_of_birdthResponse")]
        void set_Date_of_birdth(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_Date_of_birdth", ReplyAction="http://tempuri.org/ServAuthor/set_Date_of_birdthResponse")]
        System.Threading.Tasks.Task set_Date_of_birdthAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_Information", ReplyAction="http://tempuri.org/ServAuthor/get_InformationResponse")]
        string get_Information();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/get_Information", ReplyAction="http://tempuri.org/ServAuthor/get_InformationResponse")]
        System.Threading.Tasks.Task<string> get_InformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_Information", ReplyAction="http://tempuri.org/ServAuthor/set_InformationResponse")]
        void set_Information(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/set_Information", ReplyAction="http://tempuri.org/ServAuthor/set_InformationResponse")]
        System.Threading.Tasks.Task set_InformationAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/getAllAuthors", ReplyAction="http://tempuri.org/ServAuthor/getAllAuthorsResponse")]
        string getAllAuthors(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/getAllAuthors", ReplyAction="http://tempuri.org/ServAuthor/getAllAuthorsResponse")]
        System.Threading.Tasks.Task<string> getAllAuthorsAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/SaveAuthor", ReplyAction="http://tempuri.org/ServAuthor/SaveAuthorResponse")]
        void SaveAuthor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/SaveAuthor", ReplyAction="http://tempuri.org/ServAuthor/SaveAuthorResponse")]
        System.Threading.Tasks.Task SaveAuthorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/DeleteAuthor", ReplyAction="http://tempuri.org/ServAuthor/DeleteAuthorResponse")]
        void DeleteAuthor(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/DeleteAuthor", ReplyAction="http://tempuri.org/ServAuthor/DeleteAuthorResponse")]
        System.Threading.Tasks.Task DeleteAuthorAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/UpdateAuthor", ReplyAction="http://tempuri.org/ServAuthor/UpdateAuthorResponse")]
        void UpdateAuthor(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServAuthor/UpdateAuthor", ReplyAction="http://tempuri.org/ServAuthor/UpdateAuthorResponse")]
        System.Threading.Tasks.Task UpdateAuthorAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServAuthorChannel : LibraryClient.Author.ServAuthor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServAuthorClient : System.ServiceModel.ClientBase<LibraryClient.Author.ServAuthor>, LibraryClient.Author.ServAuthor {
        
        public ServAuthorClient() {
        }
        
        public ServAuthorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServAuthorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServAuthorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServAuthorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_MyHuman() {
            return base.Channel.get_MyHuman();
        }
        
        public System.Threading.Tasks.Task<string> get_MyHumanAsync() {
            return base.Channel.get_MyHumanAsync();
        }
        
        public void set_MyHuman(string value) {
            base.Channel.set_MyHuman(value);
        }
        
        public System.Threading.Tasks.Task set_MyHumanAsync(string value) {
            return base.Channel.set_MyHumanAsync(value);
        }
        
        public string get_Date_of_birdth() {
            return base.Channel.get_Date_of_birdth();
        }
        
        public System.Threading.Tasks.Task<string> get_Date_of_birdthAsync() {
            return base.Channel.get_Date_of_birdthAsync();
        }
        
        public void set_Date_of_birdth(string value) {
            base.Channel.set_Date_of_birdth(value);
        }
        
        public System.Threading.Tasks.Task set_Date_of_birdthAsync(string value) {
            return base.Channel.set_Date_of_birdthAsync(value);
        }
        
        public string get_Information() {
            return base.Channel.get_Information();
        }
        
        public System.Threading.Tasks.Task<string> get_InformationAsync() {
            return base.Channel.get_InformationAsync();
        }
        
        public void set_Information(string value) {
            base.Channel.set_Information(value);
        }
        
        public System.Threading.Tasks.Task set_InformationAsync(string value) {
            return base.Channel.set_InformationAsync(value);
        }
        
        public string getAllAuthors(string num) {
            return base.Channel.getAllAuthors(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllAuthorsAsync(string num) {
            return base.Channel.getAllAuthorsAsync(num);
        }
        
        public void SaveAuthor() {
            base.Channel.SaveAuthor();
        }
        
        public System.Threading.Tasks.Task SaveAuthorAsync() {
            return base.Channel.SaveAuthorAsync();
        }
        
        public void DeleteAuthor(string index) {
            base.Channel.DeleteAuthor(index);
        }
        
        public System.Threading.Tasks.Task DeleteAuthorAsync(string index) {
            return base.Channel.DeleteAuthorAsync(index);
        }
        
        public void UpdateAuthor(string index) {
            base.Channel.UpdateAuthor(index);
        }
        
        public System.Threading.Tasks.Task UpdateAuthorAsync(string index) {
            return base.Channel.UpdateAuthorAsync(index);
        }
    }
}
