//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClient.Status {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Status.ServStatus")]
    public interface ServStatus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/get_Name", ReplyAction="http://tempuri.org/ServStatus/get_NameResponse")]
        string get_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/get_Name", ReplyAction="http://tempuri.org/ServStatus/get_NameResponse")]
        System.Threading.Tasks.Task<string> get_NameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/set_Name", ReplyAction="http://tempuri.org/ServStatus/set_NameResponse")]
        void set_Name(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/set_Name", ReplyAction="http://tempuri.org/ServStatus/set_NameResponse")]
        System.Threading.Tasks.Task set_NameAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/get_Discription", ReplyAction="http://tempuri.org/ServStatus/get_DiscriptionResponse")]
        string get_Discription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/get_Discription", ReplyAction="http://tempuri.org/ServStatus/get_DiscriptionResponse")]
        System.Threading.Tasks.Task<string> get_DiscriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/set_Discription", ReplyAction="http://tempuri.org/ServStatus/set_DiscriptionResponse")]
        void set_Discription(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/set_Discription", ReplyAction="http://tempuri.org/ServStatus/set_DiscriptionResponse")]
        System.Threading.Tasks.Task set_DiscriptionAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/getAllStatuses", ReplyAction="http://tempuri.org/ServStatus/getAllStatusesResponse")]
        string getAllStatuses(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/getAllStatuses", ReplyAction="http://tempuri.org/ServStatus/getAllStatusesResponse")]
        System.Threading.Tasks.Task<string> getAllStatusesAsync(string num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/SaveStatus", ReplyAction="http://tempuri.org/ServStatus/SaveStatusResponse")]
        void SaveStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/SaveStatus", ReplyAction="http://tempuri.org/ServStatus/SaveStatusResponse")]
        System.Threading.Tasks.Task SaveStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/DeleteStatus", ReplyAction="http://tempuri.org/ServStatus/DeleteStatusResponse")]
        void DeleteStatus(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/DeleteStatus", ReplyAction="http://tempuri.org/ServStatus/DeleteStatusResponse")]
        System.Threading.Tasks.Task DeleteStatusAsync(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/UpdateStatus", ReplyAction="http://tempuri.org/ServStatus/UpdateStatusResponse")]
        void UpdateStatus(string index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServStatus/UpdateStatus", ReplyAction="http://tempuri.org/ServStatus/UpdateStatusResponse")]
        System.Threading.Tasks.Task UpdateStatusAsync(string index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServStatusChannel : LibraryClient.Status.ServStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServStatusClient : System.ServiceModel.ClientBase<LibraryClient.Status.ServStatus>, LibraryClient.Status.ServStatus {
        
        public ServStatusClient() {
        }
        
        public ServStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_Name() {
            return base.Channel.get_Name();
        }
        
        public System.Threading.Tasks.Task<string> get_NameAsync() {
            return base.Channel.get_NameAsync();
        }
        
        public void set_Name(string value) {
            base.Channel.set_Name(value);
        }
        
        public System.Threading.Tasks.Task set_NameAsync(string value) {
            return base.Channel.set_NameAsync(value);
        }
        
        public string get_Discription() {
            return base.Channel.get_Discription();
        }
        
        public System.Threading.Tasks.Task<string> get_DiscriptionAsync() {
            return base.Channel.get_DiscriptionAsync();
        }
        
        public void set_Discription(string value) {
            base.Channel.set_Discription(value);
        }
        
        public System.Threading.Tasks.Task set_DiscriptionAsync(string value) {
            return base.Channel.set_DiscriptionAsync(value);
        }
        
        public string getAllStatuses(string num) {
            return base.Channel.getAllStatuses(num);
        }
        
        public System.Threading.Tasks.Task<string> getAllStatusesAsync(string num) {
            return base.Channel.getAllStatusesAsync(num);
        }
        
        public void SaveStatus() {
            base.Channel.SaveStatus();
        }
        
        public System.Threading.Tasks.Task SaveStatusAsync() {
            return base.Channel.SaveStatusAsync();
        }
        
        public void DeleteStatus(string index) {
            base.Channel.DeleteStatus(index);
        }
        
        public System.Threading.Tasks.Task DeleteStatusAsync(string index) {
            return base.Channel.DeleteStatusAsync(index);
        }
        
        public void UpdateStatus(string index) {
            base.Channel.UpdateStatus(index);
        }
        
        public System.Threading.Tasks.Task UpdateStatusAsync(string index) {
            return base.Channel.UpdateStatusAsync(index);
        }
    }
}
